### ISSUE TITLE
plt.imsave index error

### ISSUE THREAD

**Issue by n12ikip12ain** [iamkrut/image_inpainting_resnet_unet#1]
Hi,
After finishing the first epoch, I am getting an Index error.

 File "train.py", line 92, in train_net
    plt.imsave(join(data_dir, 'samples', image), images[index,:,:,:3])
IndexError: index 1 is out of bounds for dimension 0 with size 1

This is with your code with no changes. Did you have these issues?

**Comment by n12ikip12ain** [comment]
i changed the index to 0 and got an Type Error still for the same line.

**Comment by iamkrut** [comment]
@n12ikip12ain did you figure the issue out. This code was for one of my university assignments and hasn't been maintained ever since. You might be able to fix it by looking into how many dimensions the `images` list has and modifying the list slicing in `plt.imsave(join(data_dir, 'samples', image), images[index,:,:,:3])` based on that.

**Comment by n12ikip12ain** [comment]
yeah i fixed it. I had to change the index to 0, and then had to adjust images=img_tensor.cpu().numpy() this line to create a numpy array.
